# Generated by Django 6.0.5 on 2026-05-15 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zona',
            name='mesas',
        ),
        migrations.AddField(
            model_name='mesa',
            name='estado_mesa',
            field=models.CharField(choices=[('libre', 'Libre'), ('ocupada', 'Ocupada'), ('reservada', 'Reservada')], default='libre', max_length=20),
        ),
        migrations.AddField(
            model_name='mesa',
            name='height',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='mesa',
            name='width',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='mesa',
            name='x',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='mesa',
            name='y',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='mesa',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesas_set', to='usuarios.zona'),
        ),
        migrations.AddField(
            model_name='zona',
            name='height',
            field=models.IntegerField(default=150),
        ),
        migrations.AddField(
            model_name='zona',
            name='shape',
            field=models.CharField(choices=[('rectangle', 'Rectángulo'), ('l-shape', 'Forma de L'), ('u-shape', 'Forma de U'), ('triangle', 'Triángulo'), ('hexagon', 'Hexágono')], default='rectangle', max_length=20),
        ),
        migrations.AddField(
            model_name='zona',
            name='width',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='zona',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zona',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
