# Generated by Django 6.0.5 on 2026-05-17 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='editable_hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.mesa'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='pedido',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserva', to='usuarios.pedido'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='pedido_enviado_cocina',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserva',
            name='recargo_reserva',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='zona',
            name='shape',
            field=models.CharField(choices=[('rectangle', 'Rectángulo'), ('l-shape', 'Forma de L'), ('triangle', 'Triángulo'), ('hexagon', 'Hexágono')], default='rectangle', max_length=20),
        ),
    ]
